site_name: Calm.io Docs
site_description: Your guide to using the Calm CLI
theme_dir: test_theme
markdown_extensions:
- admonition

pages:
- ['index.md', 'Introduction']
- ['Subcommands.md', 'Subcommands']
- ['blueprint.md', 'Blueprint']
- ['application.md', 'Application']



