site_name: calm.io Setting Up the Calm AWS AMI
site_description: This guide helps you setup up a Calm AWS AMI instance
theme_dir: testtheme
markdown_extensions:
 - admonition
 - codehilite
pages:
- ['index.md', 'Overview']
- ['before_you_begin.md', 'Before You Begin']
- ['launching_ami.md', 'Launching the Calm AWS AMI']
- ['accessing_your_calm_ami.md', 'Accessing Your Calm AMI']
- ['setting_up_calm.md', 'Setting up Calm']
